version: '3.7'

services:
  backend:
    container_name: ${PROJECT_NAME}_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
     - "5000:5000"
    env_file:
      - .env
    volumes:
      - './api/:/usr/app'

  frontend:
    container_name: ${PROJECT_NAME}_frontend
    build: ./frontend
    command: yarn start
    volumes:
      - ./frontend/:/usr/app
      - /usr/app/node_modules
    ports:
      - 8000:8000
    env_file:
      - .env

  nginx:
    container_name: ${PROJECT_NAME}_nginx
    image: nginx:latest
    env_file:
      - .env
    ports:
      - 80:80
      - 443:443
    depends_on:
      - backend
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/opt/services/backend/static
      - media_volume:/opt/services/backend/media

volumes:
  static_volume:  # <-- declare the static volume
  media_volume:  # <-- declare the media volume
